### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by Tombodil** [Tombodil/Trope22#1]
Googlefonts Additions need to be tested.

**Comment by akallish** [comment]
@Tombodil Thank you

**Comment by Tombodil** [comment]
@akallish 
Custom fonts can be uploaded as described. 
Noto Sans is actually available in Squarespace's own font library. I've set it as default and will be adjusting the styles as pages are built.

**Comment by akallish** [comment]
@Tombodil Interesting. Font libraries seem to be open sourced now so it is good that it is integrated into SquareSpace. How many weights does it have?

**Comment by Tombodil** [comment]
@akallish 

General mix of display and condensed. Img attached with the font family options.

**Comment by Tombodil** [comment]
![Uploading 16517141167756795990352229191332.jpg…]()

**Comment by Tombodil** [comment]
![snipNoto](https://user-images.githubusercontent.com/36061390/166851969-c4436d07-6471-4300-a735-0e1156df0f63.png)

**Comment by akallish** [comment]
@Tombodil Thanks for the screen grab, but I do not see the full family of weights. I only see condensed. Can you send the full list? Thanks

**Comment by Tombodil** [comment]
got the downloads and the fonts are updated. Closing this for housekeeping purposes.
