### ISSUE TITLE
Animated Gifs

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#10]
Hey @Tombodil :

[Here are test animated gifs](https://drive.google.com/drive/folders/1Rg6LJUSDXR3jpTQalciqkM1-p-GRJiGG?usp=sharing). One was exported out of Keynote but in the shape of a slide and then I edited it in Photoshop and cropped it tighter. Let me know which works.

Best,
Adam

**Comment by Tombodil** [comment]
hey Adam, Per the call I was hoping for the 'nested arrow diagram' (slide 1 background from Activation), exported with 3000px width as this would be a realistic max size. Keep the aspect ratio you built it in, because I can scale it from there.

**Comment by akallish** [comment]
@Tombodil Here you go
![Arrow_Background](https://user-images.githubusercontent.com/35602533/180887104-57346141-71df-4809-b7d3-c14523a02782.jpg)
!

**Comment by akallish** [comment]
@Tombodil Good Morning. 

I reexported the animated gifs at extra large so hopefully this improves resolution. They are in the same folder as the other gifs. Let me know if these are better. Thanks

**Comment by Tombodil** [comment]
These are much better and I've placed them with internal html formatting to crop. However, feel free to sample them larger and then crop to size. This is not necessary. The ones you provided look clean and the text is scaling fairly clearly. 

I will have details on these sent along with the update notes I'll be dropping in about an hour.

**Comment by akallish** [comment]
@Tombodil thank goodness

**Comment by akallish** [comment]
Hello @Tombodil 

Uploaded to Drive in Animated Assets

Triangle_Rev_Large_Cropped.gif
Process_Rev_Cropped_Large.gif
