### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#11]
[Here is my PDF and vcf card for downloads on my page](https://drive.google.com/drive/folders/1lt1eZ1zKiCmZ9OgqCkzw2_KGrn0Cgd4S?usp=sharing). 

My linkedin link is https://www.linkedin.com/in/kallish01/

Best,
Adam

**Comment by Tombodil** [comment]
grabbed these, will get these added tomorrow.

Will do the same once the bio and card for Liz is available.
