### ISSUE TITLE
Inspirations Home Content

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#12]
@Tombodil Please look at the GDrive Google Doc for content that should be in each of the four squares. There should be a roll-over state like the B Levels with these types of squares. Maybe the roll-over state has the extended text descriptions?

**Comment by Tombodil** [comment]
@akallish 

Missed that, corrected it. I got the squares with a corrected rollover state. The base content is what was provided with the pdf. The rollover state is using the expanded text as per the written content document.
