### ISSUE TITLE
Some replacement and new assets

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#14]
Hey @Tombodil 

Good meeting tonight.

As promised below you will find links to the new or replacement assets for the web pages we discussed.

Nexum and ZeroZero Gif Builder Files
(in animated assets folder)
https://drive.google.com/drive/folders/1Rg6LJUSDXR3jpTQalciqkM1-p-GRJiGG?usp=sharing

WW Grainger Safety Manager jpegs with new explanation of images
https://drive.google.com/drive/folders/1c9Kn-5CrqfFIMT9gLYTZFI9CT7fSu5LT?usp=sharing

iARM Youtube video link 
https://www.youtube.com/watch?v=k_S5VRRn-Ag

**Comment by Tombodil** [comment]
- Grainger images and descriptions replaced.
- Nexum and Zero Zero gifs implemented, tested.
- iArm youtube video embedded into 'Impacts and Outcomes' section of the iArm project page.
