### ISSUE TITLE
Blog Header

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#15]
Hello @Tombodil :

I visited the blog and am somewhat confused.

I was expecting the masthead to be in the same style as the website. 

Can we have "Tropisms" in the same size, color and font as "Trope Collaborative"?
Can wee have "Thoughts from the center and the edge on design, technology, and the social behaviors that are affected by both." the same same size, color and font as the subhead on the home page?

**Comment by Tombodil** [comment]
### Blog Header Update
_Where Tom forgot how to host custom files for wordpress_

Blog header fixed. I had it set and then forgot to double check the url pointers and css links. So when I stopped editing, the changes went away. I fixed it now. Screenshot attached. This uses the exact formatting from the main site. 

![blog_header_edits](https://user-images.githubusercontent.com/36061390/185282489-87cd1287-a835-45fa-89eb-482b185249bc.png)

**Comment by akallish** [comment]
@Tombodil perfect
