### ISSUE TITLE
Fee Breakdown and Negotiation

### ISSUE THREAD

**Issue by Tombodil** [Tombodil/Trope22#16]
Adam,

### Thanks for the work. Pay breakdown follows. 

_The original estimation was laughable and based off of an expectation that much of the site could just be 'ported over'.... until it became clear everything would be custom coded with full breakdown behavior and mobile specific formatting._

_I hate upcharging people, so you're gonna have the clear upper hand in us finalizing a fee._

----------------------------------------------------------------

Hours spent building the site to a rough state. 
20+ Hours 

Hours refining the site, making changes and revisions as necessary.
20+ Hours 

Hours spent on breakdown formatting + mobile formatting and changes.
20+ Hours

Total time on this project from start to completion 60+ hours. 

This isn't including the time spent due to squarespace editor updates and any time spent learning new things. Those two things are 100% my responsibility. 

Original estimation of 20 hours worked out to 600. Meaning the cost accrued would be 1800 total. ...which is embarrassing for me. That's a 200% upcharge ON TOP OF the estimation

---------------------

Can you meet me halfway between costs accrued and my busted initial estimation? 

**That would be a 1200 fee total.** 

----------------------

I'd be happy there and just learn the lesson on hours estimation. It had been too long since I did web dev and I apparently made that estimation in the grips of some sort of fever dream.

I don't know where else you could get a site this custom for 1200 flat. If that's unfair to you, please counteroffer. 

Tom

**Comment by akallish** [comment]
Hello @Tombodil :

Thanks for the breakdown of fees. I agree that it is unfortunate and will pay the $1200 to close out this project.

Best,
Adam

**Comment by Tombodil** [comment]
Tyvm

**Comment by akallish** [comment]
@Tombodil I just sent you $1200 via PayPal.

Let's have some fun in your world in creating the steam punk girl with a scottie!
