### ISSUE TITLE
Site Ownership and Eventual Transfer

### ISSUE THREAD

**Issue by Tombodil** [Tombodil/Trope22#3]
Like WIX, 
I can add people on with differing levels of access to the site. 
I've added you as a full administrator. This is necessary for me to transfer ownership of the site to you. 
There should be an email with the invite. 
-------------------------------------------
This issue will also track ownership transfer once ready.

**Comment by akallish** [comment]
@Tombodil Can you elaborate on this task?

Which SquareSpace plan do you want me to sign up for?

Do you need my login credentials?

**Comment by Tombodil** [comment]
Right now, nothing is needed.

Once I get the site more built I can transfer ownership to you for a business subscription. Currently that's displaying at $23 per month. I have a trial period active for two weeks so there's no need to spend any money yet. I can fully test any features while I build.

I should not need your credentials. I can be set as a developer with administration privileges. This is within the options menu. I can post a simple tutorial for it.

**Comment by akallish** [comment]
@Tombodil I went into settings and you have full access. Am I missing something?

I will purchase the $23 a month plan
