### ISSUE TITLE
Site Main Page Types Built

### ISSUE THREAD

**Issue by Tombodil** [Tombodil/Trope22#4]
This is the tracking of the implementation of each of the main page types. These will be tested for feedback before same level pages are created.

- Main Page *Incoming*
- Interest Areas 
- Inspiration (links Pages) (This is the same tech as the Publishing menu page, same as Solving menu page)
- Published Sub Level + Sub level with Video
- Instagram Page
- Solving Page

**Comment by akallish** [comment]
@Tombodil Thanks for the main page types. Look for improvements.

**Comment by Tombodil** [comment]
Page types are all built locally with code functions. 
I'm now in the process of adding these code blocks into the squarespace backend. 

First few pages types have gone up with minimal headaches. Mostly just some ref headers and some file adjustments needed per page. Formatting incoming as I want to get the content up first and format through the theme editor. 

Pages will be up within the next few days, ETA pages ready for formatting checks by Wed 1st June.

**Comment by Tombodil** [comment]
all page types are built and we're doing formatting. I'll begin building all the tertiary pages after tomorrow. I'm closing this as it was an older issue
