### ISSUE TITLE
Trope Website Content

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#7]
Hey Tom

I have created a Google Doc with the content for the home page elements as well as changes to the blog.

https://docs.google.com/document/d/1HMMKFD-qi341cRV7aP9DyUMzfuCx2fwbU5nmvUSoYQg/edit

**Comment by Tombodil** [comment]
confirmed I have access, I've been using an older local copy for testing but will switch to the current living document and double check the content I've already ported.

**Comment by akallish** [comment]
@Tombodil here is revised Liz bio content

A creative director who connects business, brand and market opportunities, Elizabeth creates design systems that embody an organization's most authentic and aspirational qualities. She has dedicated her career to harmonizing physical spaces, events, digital platforms and print communications to optimize organizations to the markets they serve.

Elizabeth has held design leadership positions in public relations, design and corporate entities such as Northern Trust, and Shedd Aquarium, connecting design to core organizational functions.

Practice Areas
• design leadership
• brand strategy
• brand design
• content development
• environmental design
