### ISSUE TITLE
Ongoing updates to launch - Notes and feedback

### ISSUE THREAD

**Issue by Tombodil** [Tombodil/Trope22#9]
### Ongoing changes and updates

Changes per 7/17 meeting and other assorted changes
===================================
HEADER
-"Go" shortened, text centered, alignment adjusted to new 140px area margin (even margins r/l). 
--Dropdown adjusted to match tagline alignment. 
--Full logic for header adjusted, now arrows highlight when category hovered or selected. 
--'Go' has correct hover state.
 
CAROUSELS
-carousel background area black
--arrows stronger needs rollover
--- FIXED sqaurespace margin calc: page + 3vw padder + internal component padding. That was a surprise geometry problem!

CONTACT FORM / FOOTER
-adjusted margins to new menu size and position, internal margins and layout adjusted. 
-removed the bottom border on the social media links
-left text line break standardized
-Fields now stay white with user input
-Submit button becomes blue when all fields are filled
--actual data validation is handled by squarespace, this is visual, but all fields ARE required and type is validated
-Footer text is now grey and aligns with form content

HOME PAGE
-Footer test made grey and aligned with page layout
-content margins for content blocks hard coded to 140px;
-Left alignment adjusted
--overlay aligns with main content, everything flush left
--choices are width of 'trope collaborative'
---carousel dot replaced with a good icon

QUOTES FUNCTION -logic done
-quote white and reduced leading to 1.2em
-kept italic
--title of quoted person - changed to blue, can be removed

LANDING PAGE SORTING
-tabs are white on blue
-reset is black with white text
-reset is hidden until a choice is made

PUBLISHED PAGE - Agile
-removed space between title and subtitle

PUBLISHING LANDING PAGE
--Blurbs added

INTEREST AREAS
-Sub Title removed and text brought in alignment with left padding
description copy is now grey
-Description is flush left on the sub cat line ONLY if over 1300px screen width. otherwise it's the original size (for mobile readability).
--right margin to arrows added
--arrows are correctly aligned and spaced based on monospace type

INTERVIEWS
-Kept leader lines
-Interview link on line break and formatted
-Publication title is bold
--Sub Titles given line breaks where needed.
-All img icons given specific css formatting to keep aspect ratio,  currently 100px wide.

--Added new interview with link

CASE STORIES LANDING

CASE STORIES (Current Example Aurora)
-Sub cat are H3 and no leader lines
--back chevron on left, right chevron on right
--Chevrons now change color with the hover state

INSPIRATION (LINKS LANDING)
-Broken Links removed, correct links checked and links added
--Added new blubs

INSTAGRAM

BLOG LINK

**Comment by akallish** [comment]
Hello Tom:

Good Morning. I went through the current iteration and have the following comments. Also have some screen grabs to show some visual or functional problems

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home

• Hamburger needs to be fixes in terms of width
• Contact form should align with the content in the red rectangle

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Interviews

• Should have a slash after Publishing
• the arrows are not accurate and look too thin
• Back and Next should align visually vertically

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Inspirations

• New content and old content has not been updated

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Tag Filters

• The new solution is good
• I get weird pop up boxes when I select a filter

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interviews

• Fixes much better
• Put some space between soundcloud link and the content for "Design In The Moment 85"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• + and - are better

**Comment by akallish** [comment]
![Screen Shot 2022-07-22 at 8 51 17 AM](https://user-images.githubusercontent.com/35602533/180456017-957811dc-174c-476a-ac08-ee074e67d1a4.jpg)
![Screen Shot 2022-07-22 at 8 55 11 AM](https://user-images.githubusercontent.com/35602533/180456021-6010a79c-f557-474e-b80c-7ef67af75c69.jpg)

**Comment by Tombodil** [comment]
Got the feedback, saw the pics too. I can trace back and sort these issues
tonight. I'll update the github issue with the fixes and further changes
later tonight.

**Comment by akallish** [comment]
@Tombodil i figured as much

**Comment by akallish** [comment]
@Tombodil 

I looked at the current iteration of the build and it is coming along nicely.

Home
• Social media icons are stacked in default browser state. See image. 

Inspirations
• Delete Living Principles
• Delete WebSmart TV

Interest Areas
• Use the back like on Auror
![Home_SocialMedia_SNAFU](https://user-images.githubusercontent.com/35602533/180613744-fe5036b9-d724-4deb-8214-f46fe798cf80.jpg)
![Home_SocialMedia_SNAFU](https://user-images.githubusercontent.com/35602533/180613744-fe5036b9-d724-4deb-8214-f46fe798cf80.jpg)
![Home_SocialMedia_SNAFU](https://user-images.githubusercontent.com/35602533/180613756-54ca9e0e-7756-4c52-8f9c-aba15f978de3.jpg)
![Home_SocialMedia_SNAFU](https://user-images.githubusercontent.com/35602533/180613756-54ca9e0e-7756-4c52-8f9c-aba15f978de3.jpg)
a
